SELECT DISTINCT C.ITEM_ID, C.ORIGEN_ID
FROM VENTASDB.VTA_FACT_ITEMS A
INNER JOIN INVDB.INV_ITEMS B ON B.ITEM_ID = A.ITEM_ID
INNER JOIN SYNC.INV_ITEMS C ON C.ITEM_ID = B.ITEM_ID
WHERE FACT_ID = :FACT_ID AND EMP_ID = :EMP_ID